baseURL      = "https://film.fyi/"
title        = "Film.Fyi"
disableKinds = ["section", "taxonomy", "term"]

[params]
    # Enables Plausible.io Analytics.
    plausible_domain = "film.fyi"

    [params.gallerydeluxe]
        shuffle = true
        reverse = true
        enable_exif = true 	# See https://gohugo.io/content-management/image-processing/#exif-data for how to filter tags.

[caches]
    [caches.images]
        dir    = ':cacheDir/gallerydeluxe'
        maxAge = "4320h"                   # 6 months.

[imaging]
    resampleFilter = "CatmullRom"
    quality        = 71
    anchor         = "smart"
    [imaging.exif]
        disableDate    = false
        disableLatLong = true
        includeFields  = 'Artist|LensModel|FNumber|ExposureTime'

[server]
    [[server.headers]]
        for = '/**'
        [server.headers.values]
            Referrer-Policy = 'strict-origin-when-cross-origin'

[module]
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "layouts"
        target = "layouts"
    [[module.mounts]]
        source = "content"
        target = "content"
    [[module.mounts]]
        source = "static"
        target = "static"
    [[module.mounts]]
        source = '/Users/melroser/Pictures/ImageExport'
        target = 'content/images'
    [[module.imports]]
        path = "github.com/bep/gallerydeluxe"
